kind: pipeline
name: Frontend latest lint

steps:
- name: lint
  image: node:latest
  commands:
  - npm install
  - npm run lint

---

kind: pipeline
name: Frontend version lint

steps:
- name: lint
  image: node:11
  commands:
  - npm install
  - npm run lint

---

kind: pipeline
name: Frontend latest build

steps:
- name: build
  image: node:latest
  commands:
  - npm install
  - npm run build

---

kind: pipeline
name: Frontend version build

steps:
- name: build
  image: node:11
  commands:
  - npm install
  - npm run build

