language: node_js

node_js:
  - "11"

install:
  - npm install

script:
  - bash shell/master.sh

branches:
  only:
    - master
    - dev

notifications:
  email:
    - lucien@lucien.ink

addons:
  hosts:
    - ${WEBHOOK}
