language: node_js

node_js:
  - "11"

install:
  - npm install

script:
  - npm run build

after_success:
  - bash shell/${BRANCH}.sh

branches:
  only:
    - master

notifications:
  email:
    - lucien@lucien.ink
  on_failure: always

env:
  global:
    - GH_REF: github.com/LucienShui/PasteMeFrontend.git
    - GH_PASTEME: github.com/LucienShui/PasteMe.git
    - P_BRANCH: build

addons:
  hosts:
    - ${WEBHOOK}
