language: node_js

node_js:
  - "11"

install:
  - npm install

script:
  - bash shell/${TRAVIS_BRANCH}.sh

branches:
  only:
    - master
    - dev

notifications:
  email:
    - ${NOTIFY_EMAIL}

addons:
  hosts:
    - ${WEBHOOK}
